name: Deploy Docker Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Instalar o SSH Client
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 4. Copiar arquivos para o EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=300 ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            set -e

            echo "Conectando ao servidor EC2..."

            REPO_DIR="/home/ec2-user/tech-challenge-02" # Diretório do repositório

            # Instalar dependências se necessário
            echo "Verificando dependências..."
            if ! command -v docker &> /dev/null; then
              echo "Docker não encontrado. Instalando Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo systemctl enable docker
            fi

            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose não encontrado. Instalando Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Preparar repositório
            echo "Preparando repositório..."
            if [ ! -d "$REPO_DIR" ]; then
              echo "Diretório não encontrado. Clonando o repositório..."
              git clone https://github.com/fonaziero/tech-challenge-02.git $REPO_DIR
            fi

            cd $REPO_DIR
            echo "Atualizando repositório..."
            git reset --hard
            git pull origin main

            # Rodar Docker Compose
            echo "Executando docker-compose..."
            sudo docker system prune -f -a
            docker-compose down || true
            docker-compose up -d --build

            echo "Deploy concluído com sucesso!"
          EOF
 